### PR TITLE
Experimental fix to reset global static state per test method

### PR DESCRIPTION
**Pull request by angularsen**
Move unit abbreviation strings into culture-specific resource files by tmilnthorp · Pull Request \#1210 · angularsen/UnitsNet
https://github.com/angularsen/UnitsNet/pull/1210

### CODE REVIEW

**Comment by tmilnthorp** [comment]
@angularsen I'm not sure this is the right approach. Do we guarantee thread safety? The existence of concurrent dictionaries and locking mechanisms indicate that we do. This is revealing a legitimate threading bug.

**Comment by angularsen** [comment]
The way I see it, the problem is less about concurrency issues and more about storing unit conversion functions, abbreviation lookups etc. in static fields.

The way UnitsNet is designed and used, I don't see any other way than storing config in static fields. Requiring a factory to construct quantities would feel out of place.

Xunit runs test classes concurrently by default, while test methods in a class are run sequentially.
Xunit test classes don't run in app domain isolation, so static fields are shared across both test methods and test classes. This is why some tests fail on first run, then succeed on next run. It depends on what tests run first.

One alternative approach is to force sequential execution of test classes that share static config, which I think is pretty much all of them. Then they could clean up after themselves as in this PR. 
The downside is slower tests, the upside is reduced complexity in the implementation.

**Comment by tmilnthorp** [comment]
@angularsen what if we inject an instance of the quantity infos, or quantity, class into the abbreviation cache? Default (null) could fallback to the static instance.

**Comment by angularsen** [comment]
I think I see what you mean now. The culprit is this, right?

Instance method `UnitAbbreviationsCache.PerformAbbreviationMapping` calls static method `Quantity.TryGetUnitInfo`, which means tests that create a new `UnitAbbreviationsCache` instance is still affected by global static state.

Yes, this seems like a flaw. The `UnitAbbreviationsCache` should require all its dependencies to be injected, then `UnitAbbreviationsCache.Default` would inject the default static state.

This is a minimal repro of one successful and one failed test due to shared static state:
image

### The global state
The dependency tree of mutable state looks something like this, unless I forgot something.

Mutable state and dependents:
- `UnitInfo.AbbreviationsMap` (read/write + lazy), stored in `QuantityInfo` per quantity, such as `Length.Info`
	- `UnitAbbreviationsCache.Default` (read/write mutating `UnitInfo`)
  		- `UnitParser.Default` (read-only)
  		- `QuantityParser.Default` (read-only)
- `UnitConverter.Default` (read/write)

So in essence, the mutable global state is abbreviations in `UnitInfo` and conversion functions in `UnitConverter`.

We seem to have done a decent job not manipulating global state in tests already, I only found one test violating this:
`UnitAbbreviationsCacheTests.MapUnitToDefaultAbbreviation_GivenCustomAbbreviation_SetsAbbreviationUsedByQuantityToString`

If we fix that `UnitAbbreviationsCache` instance methods don't look up static state in `Quantity.TryGetUnitInfo`, when maybe all the problems go away.

**Pull request closed without merging**
